version: "3.6"             
services:
  db:                      
    image: mariadb:10.2    
    env_file: .env
    container_name: ${COMPOSE_PROJECT_NAME:-omp}_db 
    restart: always
  omp:                    
    image: lucasdiedrich/omp:master
    env_file: .env
    container_name: ${COMPOSE_PROJECT_NAME:-pkp}_omp
    hostname: ${COMPOSE_PROJECT_NAME:-pkp_omp} 
    restart: always
    ports:
      - "${HTTP_PORT:-8085}:80" 
      - "${HTTPS_PORT:-8445}:443"
    volumes:
     - /etc/localtime:/etc/localtime           
    #- ./files/private:/var/www/files 
    #- ./files/public:/var/www/html/public  
    #- ./files/logs:/var/log/apache2   
    #- ./config/omp.config.inc.php:/var/www/html/config.inc.php  
    #- ./config/apache.htaccess:/var/www/html/.htaccess  
    #- ./config/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on: 
     - db
    # labels:
      # - traefik.frontend.rule=Host:${PROJECT_DOMAIN:-myserver.mydomain}
      # - traefik.docker.network=proxy
      # - traefik.port=80   
      # - traefik.enable=true 
    # networks:
      # - internal 
      # - proxy
      
# Adminer
# Usefull when you need to fix stuff in your omp.
#  adminer:
#    image: adminer
#    ports:
#      - ${ADMINER_HTTP:-9085}:8080
#    networks:
#      - internal
#    depends_on:
#      - db
